// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateProject(arg1:string):Promise<main.Project>;

export function DeleteProject(arg1:string):Promise<void>;

export function ExportGlobalAssets():Promise<string>;

export function ExportProject(arg1:string):Promise<string>;

export function GetAssets():Promise<any>;

export function GetPalette():Promise<any>;

export function GetProjectData(arg1:string):Promise<main.ProjectData>;

export function GetProjects():Promise<Array<main.Project>>;

export function ImportGlobalAssets(arg1:string,arg2:boolean):Promise<void>;

export function ImportProject(arg1:string,arg2:string):Promise<main.Project>;

export function SaveAssets(arg1:any):Promise<void>;

export function SavePalette(arg1:any):Promise<void>;

export function SaveProjectData(arg1:string,arg2:any):Promise<void>;

export function UpdateProjectName(arg1:string,arg2:string):Promise<void>;
