// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ExportGlobalAssets() {
  return window['go']['main']['App']['ExportGlobalAssets']();
}

export function ExportProject(arg1) {
  return window['go']['main']['App']['ExportProject'](arg1);
}

export function GetAssets() {
  return window['go']['main']['App']['GetAssets']();
}

export function GetPalette() {
  return window['go']['main']['App']['GetPalette']();
}

export function GetProjectData(arg1) {
  return window['go']['main']['App']['GetProjectData'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportGlobalAssets(arg1, arg2) {
  return window['go']['main']['App']['ImportGlobalAssets'](arg1, arg2);
}

export function ImportProject(arg1, arg2) {
  return window['go']['main']['App']['ImportProject'](arg1, arg2);
}

export function SaveAssets(arg1) {
  return window['go']['main']['App']['SaveAssets'](arg1);
}

export function SavePalette(arg1) {
  return window['go']['main']['App']['SavePalette'](arg1);
}

export function SaveProjectData(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectData'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function UpdateProjectName(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectName'](arg1, arg2);
}
